### ISSUE TITLE
Deployment System

### ISSUE THREAD

**Issue by cad448** [IT490-Tech-Team/IT490-Project#35]
Including version control, deployment, and rollback.
- [x] The creation of a package with a version number
- [x] The automatic installation of that package on your QA machine
- [x] Proof it has been deployed correctly
- [x] Then mark the package as Bad or Fail
- [x] Trigger a rollback to the last good version of that package.
- [x] Then roll out a fix to both QA and Production.
- [x] Show that QA and Production are fully functional (just enough to show login and basic functionality are present)
- [ ] Create a video and submit to **"Deployment System Proof" Assignment** on Canvas when completed. 

Additional Notes: 
We **CANNOT** use Github Actions for deployment. Examples for things we can use: basic Unix operations, RMQ to scp/rsync/ftp files around (must keep track of changes in database)

**Comment by ofelizestevez** [comment]
So far, installer.sh backend has user input with ./rabbitmq.sh then there's the commands that ask for sudo ;-;

**Comment by ofelizestevez** [comment]
Okay installer works (at least for backend)

now what's left is 
- [ ] cascade down to frontend and dmz
- [ ] package management
  - [ ] accept
  - [ ] deny
