### ISSUE TITLE
Hot Stand By System for Production

### ISSUE THREAD

**Issue by cad448** [IT490-Tech-Team/IT490-Project#37]
Backup VMs for production frontend and production backend.

- Backup frontend should have a "heartbeat" that constantly checks on the primary frontend, replacing it if it notices that the primary frontend is down.
- Backup backend should replicate the primary backend

**Comment by ofelizestevez** [comment]
Going to follow up with the professor about this,

I could, for example, set up a nextDNS server that rewrites a domain name to 2 VM IP addresses. Or maybe create a load balancer that handles request and sends them to the correct VMs.
