### ISSUE TITLE
Decentralized Logging

### ISSUE THREAD

**Issue by cad448** [IT490-Tech-Team/IT490-Project#40]
Any time the website and its components failed, it should log that error into a file. Each Stack (prod|test|dev) should have a shared log file between all 3 machines.

For the final submission: trigger a log even and show the log files on each vm getting the updated message ('tail -f mylogfile' is a good way to show it in real time)

**Comment by ofelizestevez** [comment]
re-opening since I believe this hasn't been merged to main yet.
