### ISSUE TITLE
EXTRA CREDIT: NAGIOS

### ISSUE THREAD

**Issue by cad448** [IT490-Tech-Team/IT490-Project#45]
**EXTRA CREDIT** DELIVERABLE: 
NAGIOS - agent installed on production, monitored from Deployment

**Comment by ofelizestevez** [comment]
todo

- [ ] Backend
  - [ ] mysql
- [ ] Frontend
  - [ ] website 
- [ ] DMZ
  - [ ] service

- [ ] logs (?)

**Comment by ofelizestevez** [comment]
To Monitor

- [ ] Server Uptime
- [ ] CPU Usage
- [ ] Memory Usage
- [ ] Disk Space
- [ ] Disk I/O
- [ ] Network Traffic
- [ ] Service Availability
- [ ] Custom Application Metric
